#version: "3.9"

services:
  game_backend:
    build:
      context: .
    container_name: game_backend
    environment:
      MIX_ENV: prod
      DATABASE_URL: ecto://postgres:postgres@db/game_backend_prod
      SECRET_KEY_BASE: a_super_secret
      GUARDIAN_SECRET: jwt_secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - backend_net

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game_backend_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  redis:
    image: redis:7-alpine
    networks:
      - backend_net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend_net

networks:
  backend_net:

volumes:
  postgres_data:
