apiVersion: v1
kind: Secret
metadata:
  name: game-backend-secret
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ .Values.secretEnv.SECRET_KEY_BASE | quote }}
  GUARDIAN_SECRET: {{ .Values.secretEnv.GUARDIAN_SECRET | quote }}
