{application,redix,
             [{optional_applications,[castore]},
              {applications,[kernel,stdlib,elixir,logger,ssl,telemetry,
                             castore,nimble_options]},
              {description,"Fast, pipelined, resilient Redis driver for Elixir."},
              {modules,['Elixir.Redix','Elixir.Redix.Connection',
                        'Elixir.Redix.ConnectionError',
                        'Elixir.Redix.Connector','Elixir.Redix.Error',
                        'Elixir.Redix.Format','Elixir.Redix.Protocol',
                        'Elixir.Redix.Protocol.ParseError',
                        'Elixir.Redix.PubSub',
                        'Elixir.Redix.PubSub.Connection',
                        'Elixir.Redix.SocketOwner',
                        'Elixir.Redix.StartOptions','Elixir.Redix.Telemetry',
                        'Elixir.Redix.URI']},
              {registered,[]},
              {vsn,"1.5.2"}]}.
